### ISSUE TITLE
Potential spelling error in the prompt templates

### ISSUE THREAD

**Issue by ShayekhBinIslam** [facebookresearch/motif#7]
In the prompt templates [here](https://github.com/facebookresearch/motif/blob/51b5f47312ef4cecab65ac3f0df384bc76fae555/rlaif/prompts.py#L30C47-L30C58) and [here](https://github.com/facebookresearch/motif/blob/51b5f47312ef4cecab65ac3f0df384bc76fae555/rlaif/prompts.py#L47C53-L47C64), the word `principles` is written as `princicples`.

**Comment by proceduralia** [comment]
Hi Shayekh,

Thanks for bringing this up. We are aware of this typo, but we decided to keep it in the prompts for reproducibility of the setup that was actually used to generate the dataset. In any case, LLMs are generally very robust to typos in their prompts, and I would guess that shouldn't have a significant effect on the results.

Thanks,

Pierluca

**Comment by ShayekhBinIslam** [comment]
Hi Pierluca,

Thanks for the response. Yes, the typo-robustness is expected from LLMs.

Regards,
Shayekh
