### ISSUE TITLE
Running APPO in a single process for debugging?

### ISSUE THREAD

**Issue by bamos** [facebookresearch/motif#9]
Hi @proceduralia @mklissa! Is there a way to run APPO in here in a single process for debugging without running the full distributed mode? (Or another easier way to debug it?) The latest version of sample factory has a [--serial_model](https://www.samplefactory.dev/07-advanced-topics/serial-mode/) flag but it seems like this came out after the version included in this repo

**Comment by mklissa** [comment]
Hey @bamos, unfortunately APPO in this version of sample factory doesn't have native support for it, but what we used was `ForkedPdb().set_trace()` for breakpoints (this is a good reference: https://github.com/Lightning-AI/forked-pdb). Additionally you can reduce the number of workers to make it more manageable for debugging. It is not very pretty but it works (which is also why we removed it from the official codebase)

**Comment by bamos** [comment]
That's helpful, thanks! I didn't know about forked-pdb but it's exactly what I was looking for here
